# Generated by Django 2.0.5 on 2018-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0006_auto_20180720_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='address',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
