# Generated by Django 2.0.5 on 2018-07-22 23:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0009_transactions_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=models.DateField(default=datetime.datetime(2018, 7, 22, 23, 55, 56, 910926, tzinfo=utc)),
        ),
    ]
