# Generated by Django 2.0.5 on 2018-07-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0012_profile_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
