# Generated by Django 2.0.5 on 2018-07-23 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0013_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete='models.CASCADE', primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
