# Generated by Django 2.0.5 on 2018-07-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0014_auto_20180723_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=70),
        ),
    ]
