# Generated by Django 2.0.5 on 2018-07-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0016_auto_20180724_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=70, unique=True),
        ),
    ]
