# Generated by Django 2.0.5 on 2018-07-24 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0017_auto_20180724_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodges.Zone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='lodge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodges.Lodge'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
