# Generated by Django 2.0.5 on 2018-07-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0018_auto_20180724_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
