# Generated by Django 2.0.5 on 2018-07-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0019_lodge_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='lodge',
            name='short_description',
            field=models.CharField(default='', max_length=20),
        ),
    ]
