# Generated by Django 2.0.5 on 2018-07-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0021_auto_20180730_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='base_price',
            field=models.IntegerField(default=0),
        ),
    ]
