# Generated by Django 2.0.5 on 2018-08-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0022_zone_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Rather not say', max_length=15),
        ),
    ]
