# Generated by Django 2.0.5 on 2018-08-01 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0023_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 8, 37, 27, 65867, tzinfo=utc)),
        ),
    ]
