# Generated by Django 2.0.5 on 2018-08-01 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0024_auto_20180801_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
