# Generated by Django 2.0.5 on 2018-08-03 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lodges', '0025_auto_20180801_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='potential_residents',
            field=models.ManyToManyField(related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
