# Generated by Django 2.0.5 on 2018-08-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0027_auto_20180804_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='count',
            new_name='count_lodges',
        ),
    ]
