# Generated by Django 2.0.5 on 2018-08-04 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0028_auto_20180804_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='count_lodges',
        ),
    ]
