# Generated by Django 2.0.5 on 2018-08-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0029_auto_20180804_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='base_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zone',
            name='count_lodges',
            field=models.IntegerField(default=0),
        ),
    ]
