# Generated by Django 2.0.5 on 2018-08-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0030_auto_20180804_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='count_lodges',
            new_name='count',
        ),
    ]
