# Generated by Django 2.0.5 on 2018-08-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0031_auto_20180804_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='base_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
