# Generated by Django 2.0.5 on 2018-08-10 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('lodges', '0034_auto_20180810_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='potential_residents',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests',
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
