# Generated by Django 2.0.5 on 2018-08-12 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lodges', '0035_auto_20180810_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodge',
            name='potential_residents',
        ),
        migrations.AddField(
            model_name='lodge',
            name='applicants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
