# Generated by Django 2.0.5 on 2018-08-16 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lodges', '0037_auto_20180812_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodge',
            name='applicant',
        ),
        migrations.AddField(
            model_name='lodge',
            name='applicants',
            field=models.ManyToManyField(null=True, related_name='interest', to=settings.AUTH_USER_MODEL),
        ),
    ]
